### DISCUSSION TITLE
Reusable list in one rule

### DISCUSSION THREAD

**Discussion by frack113** [SigmaHQ/pySigma#10] [Ideas]
hello,
many rule use the same patern but with other logsource.
example (a simple)
```yaml
detection:
    selection_1:
        EventID: 4104
        ScriptBlockText|re: '.*cmd.{0,5}(?:\/c|\/r).+clip(?:\.exe)?.{0,4}&&.+clipboard]::\(\s\\\"\{\d\}.+\-f.+\"'
    selection_2:
        EventID: 4103
        Payload|re: '.*cmd.{0,5}(?:\/c|\/r).+clip(?:\.exe)?.{0,4}&&.+clipboard]::\(\s\\\"\{\d\}.+\-f.+\"'
    condition: 1 of them
```
this would be 
```yaml
internal:
    my_regex : '.*cmd.{0,5}(?:\/c|\/r).+clip(?:\.exe)?.{0,4}&&.+clipboard]::\(\s\\\"\{\d\}.+\-f.+\"'
detection:
    selection_1:
        EventID: 4104
        ScriptBlockText|re: %my_regex%
    selection_2:
        EventID: 4103
        Payload|re: %my_regex%
    condition: 1 of them
```
for list
```yaml
internal:
    bad_word:
        - "get_ad"
        - "set_ad"
        - "kill_ad"
detection:
    selection_1:
        EventID: 4104
        ScriptBlockText|contains: %bad_word%
    selection_2:
        EventID: 4103
        Payload|contains: %bad_word%
    condition: 1 of them
```

So if there a update to the list / patern only one to correct 😄
