### DISCUSSION TITLE
Are there any complete examples of using 'change_logsource' in a pipeline rule?

### DISCUSSION THREAD

**Discussion by BCall-BT** [SigmaHQ/pySigma#192] [Q&A] [answered]
I'm  trying to use pipelines with sigma-cli or https://sigconverter.io/ to replace the default index patterns used when converting to an elastic siem rule. Any attempt I make either errors out or does nothing. Below is the only reference I can find, but it does not work
`name: transformation_demo
priority: 100
transformations:
    - id: prefix_source_and_index_for_puppy_logs
      type: change_logsource
      mapping:`

**Comment by joshnck** [comment, marked as answer]
```yaml
transformations:
- id: change_logsource
  type: change_logsource
  category: security
  rule_conditions:
  - type: logsource
    category: process_creation
```

That should do it for you!
