### DISCUSSION TITLE
Processing pipelines on Keyword-based detections ?

### DISCUSSION THREAD

**Discussion by EzLucky** [SigmaHQ/pySigma#339] [Q&A] [answered]
I'm trying to create a **processing pipeline to apply a default field to items of a keyword-based detection**.

But it seems that all conditions and transformations are applying on field-based detections (or attributes not related to detection).

Let's take the following sigma detection : 
```yaml
detection:
    keywords:
      - a
      - b
      - c
    condition: keywords
```

It produces, in Splunk for example : `a OR b OR c`\
I was aiming at applying a pipeline to give the following output : `my_field=a OR my_field=b OR my_field=c`.

I even  just tried to throw a SigmaTransformationError using the detection_item_failure transformation pipeline when in input I have a rule not using fields, but one more time I could not add a condition related to the keyword-based detection.

Any advice on making something work only using pipelines ?

**Comment by M3NIX** [comment]
You could try to work with the replace post processing step.
It is not a very elegant solution but that's what I got working quite fast for your example, but might fail for more complex queries.

[sigconverter.io link](https://sigconverter.io/#version=1.0.5&backend=splunk&format=default&pipeline=&rule=dGl0bGU6IFRlc3QKbG9nc291cmNlOgogICAgY2F0ZWdvcnk6IHByb2Nlc3NfY3JlYXRpb24KICAgIHByb2R1Y3Q6IHdpbmRvd3MgICAgCmRldGVjdGlvbjoKICAgIGtleXdvcmRzOgogICAgICAtIGEKICAgICAgLSBiCiAgICAgIC0gYwogICAgc2VsZWN0aW9uOgogICAgICAgIGFscmVhZHlfYV9maWVsZDogdGVzdAogICAgY29uZGl0aW9uOiBrZXl3b3JkcyBhbmQgc2VsZWN0aW9uCg%3D%3D&pipelineYml=LS0tCm5hbWU6IHRlc3QKcG9zdHByb2Nlc3Npbmc6Ci0gdHlwZTogcmVwbGFjZQogIHBhdHRlcm46ICcoPzwhXD0pIihbXiJdKikiJwogIHJlcGxhY2VtZW50OiAnbXlfbmV3X2ZpZWxkPSJcXFwxIicKLSB0eXBlOiByZXBsYWNlCiAgcGF0dGVybjogJyJcXCcKICByZXBsYWNlbWVudDogJyInCg%3D%3D)

`rule.yml`
```yml
title: Test
logsource:
    category: process_creation
    product: windows    
detection:
    keywords:
      - a
      - b
      - c
    selection:
        already_a_field: test
    condition: keywords and selection
 ```
 
 `pipeline.yml`
 ```yml
 ---
name: test
postprocessing:
- type: replace
  pattern: '(?<!\=)"([^"]*)"'
  replacement: 'my_new_field="\\\1"'
- type: replace
  pattern: '"\\'
  replacement: '"'
```

`query`:
```
my_new_field="a" OR my_new_field="b" OR my_new_field="c" already_a_field="test"
```

**Reply by EzLucky** [reply]
Nice workaround thank you @M3NIX !

The disadvantage of this solution is that the regex is SIEM-dependent.

**Reply by EzLucky** [reply]
I let the discussion opened as it may lead to a keyword-based transformation pipeline type 🤞

**Reply by EzLucky** [reply]
I corrected your answer @M3NIX to include wildcard in the generated SPL, I also included Lucene if someone needs this workaround : 

**[SPLUNK](https://sigconverter.io/#version=1.0.5&backend=splunk&format=default&pipeline=&rule=dGl0bGU6IFRlc3QKbG9nc291cmNlOgogICAgY2F0ZWdvcnk6IHByb2Nlc3NfY3JlYXRpb24KICAgIHByb2R1Y3Q6IHdpbmRvd3MgICAgCmRldGVjdGlvbjoKICAgIGtleXdvcmRzOgogICAgICAtIGEKICAgICAgLSBiCiAgICAgIC0gYwogICAgc2VsZWN0aW9uOgogICAgICAgIGFscmVhZHlfYV9maWVsZDogdGVzdAogICAgY29uZGl0aW9uOiBrZXl3b3JkcyBhbmQgc2VsZWN0aW9uCg%3D%3D&pipelineYml=LS0tCm5hbWU6IHRlc3QKcG9zdHByb2Nlc3Npbmc6Ci0gdHlwZTogcmVwbGFjZQogIHBhdHRlcm46ICcoPzwhXD0pIihbXiJdKikiJwogIHJlcGxhY2VtZW50OiAnbXlfbmV3X2ZpZWxkPSJcXFwxIicKLSB0eXBlOiByZXBsYWNlCiAgcGF0dGVybjogJyJcXCcKICByZXBsYWNlbWVudDogJyInCg%3D%3D)**

`pipeline.yml` :

```yaml
name: splunk_keyword_replacement
postprocessing:
- type: replace
  pattern: '(?<!\=)"([^"]+?)"'
  replacement: 'my_new_field="*\\\1*"'
- type: replace
  pattern: '="\*\\'
  replacement: '="*'
```

`result` :

`my_new_field="*a*" OR my_new_field="*b*" OR my_new_field="*c*"`

**[LUCENE](https://sigconverter.io/#version=1.0.5&backend=splunk&format=default&pipeline=&rule=dGl0bGU6IFRlc3QKbG9nc291cmNlOgogICAgY2F0ZWdvcnk6IHByb2Nlc3NfY3JlYXRpb24KICAgIHByb2R1Y3Q6IHdpbmRvd3MgICAgCmRldGVjdGlvbjoKICAgIGtleXdvcmRzOgogICAgICAtIGEKICAgICAgLSBiCiAgICAgIC0gYwogICAgc2VsZWN0aW9uOgogICAgICAgIGFscmVhZHlfYV9maWVsZDogdGVzdAogICAgY29uZGl0aW9uOiBrZXl3b3JkcyBhbmQgc2VsZWN0aW9uCg%3D%3D&pipelineYml=LS0tCm5hbWU6IHRlc3QKcG9zdHByb2Nlc3Npbmc6Ci0gdHlwZTogcmVwbGFjZQogIHBhdHRlcm46ICcoPzwhXD0pIihbXiJdKikiJwogIHJlcGxhY2VtZW50OiAnbXlfbmV3X2ZpZWxkPSJcXFwxIicKLSB0eXBlOiByZXBsYWNlCiAgcGF0dGVybjogJyJcXCcKICByZXBsYWNlbWVudDogJyInCg%3D%3D)**

`pipeline.yml` :

```yaml
name: lucene_keyword_replacement
postprocessing:
- type: replace
  pattern: '(?<!\:)(\*[^*]+?\*)'
  replacement: 'my_new_field:\\\1'
- type: replace
  pattern: ':\\\*'
  replacement: ':*'
```

`result` :

`my_new_field:*a* OR my_new_field:*b* OR my_new_field:*c*`


update :\
[advanced Lucene regex](https://sigconverter.io/#version=1.0.5&backend=splunk&format=default&pipeline=&rule=dGl0bGU6IFRlc3QKbG9nc291cmNlOgogICAgY2F0ZWdvcnk6IHByb2Nlc3NfY3JlYXRpb24KICAgIHByb2R1Y3Q6IHdpbmRvd3MgICAgCmRldGVjdGlvbjoKICAgIGtleXdvcmRzOgogICAgICAtIGEKICAgICAgLSBiCiAgICAgIC0gYwogICAgc2VsZWN0aW9uOgogICAgICAgIGFscmVhZHlfYV9maWVsZDogdGVzdAogICAgY29uZGl0aW9uOiBrZXl3b3JkcyBhbmQgc2VsZWN0aW9uCg%3D%3D&pipelineYml=LS0tCm5hbWU6IHRlc3QKcG9zdHByb2Nlc3Npbmc6Ci0gdHlwZTogcmVwbGFjZQogIHBhdHRlcm46ICcoPzwhXD0pIihbXiJdKikiJwogIHJlcGxhY2VtZW50OiAnbXlfbmV3X2ZpZWxkPSJcXFwxIicKLSB0eXBlOiByZXBsYWNlCiAgcGF0dGVybjogJyJcXCcKICByZXBsYWNlbWVudDogJyInCg%3D%3D) to deal with the case `already_a_field: a*b*c` --> `(?<!\:)(?:^|(?<=(?:\(|\s)))(\*[^*]+?\*)`

**Reply by EzLucky** [reply]
Update : this workaround is not working when "already_a_field" is used with "| contains" and multivalues

```yaml
title: Test
logsource:
    category: process_creation
    product: windows    
detection:
    keywords:
      - a
      - b
      - c
    selection:
        already_a_field|contains:
          - test1
          - test2
    condition: keywords and selection
```

**Comment by thomaspatzke** [comment]
Valid use case, should be easy to implement with the already existing field name mappings by allowing to map null values to something. I transfer this to an issue.

**Comment by EzLucky** [comment, marked as answer]
This pipeline is working (tested [here](https://sigconverter.io/#version=1.0.6&backend=splunk&format=default&pipeline=&rule=dGl0bGU6IFRlc3QKbG9nc291cmNlOgogICAgY2F0ZWdvcnk6IHByb2Nlc3NfY3JlYXRpb24KICAgIHByb2R1Y3Q6IHdpbmRvd3MgICAgCmRldGVjdGlvbjoKICAgIGtleXdvcmRzOgogICAgICAtIGEKICAgICAgLSBiCiAgICAgIC0gYwogICAgc2VsZWN0aW9uOgogICAgICAgIGFscmVhZHlfYV9maWVsZDogdGVzdAogICAgICAgIGFscmVhZHlfYV9maWVsZF9iaXN8Y29udGFpbnM6CiAgICAgICAgICAtIHRlc3QxCiAgICAgICAgICAtIHRlc3QyCiAgICBjb25kaXRpb246IGtleXdvcmRzIGFuZCBzZWxlY3Rpb24%3D&pipelineYml=bmFtZTogRGVmYXVsdCBmaWVsZCBuYW1lCnRyYW5zZm9ybWF0aW9uczoKICAtIGlkOiBmaWVsZF9tYXBwaW5nCiAgICB0eXBlOiBmaWVsZF9uYW1lX21hcHBpbmcKICAgIG1hcHBpbmc6CiAgICAgIG51bGw6CiAgICAgICAgLSBteV9maWVsZF9uYW1l)) :

```yaml
name: Default field name
transformations:
  - id: field_mapping
    type: field_name_mapping
    mapping:
      null:
        - my_field_name
 ```
