### DISCUSSION TITLE
How to remove fields detection in Pipeline

### DISCUSSION THREAD

**Discussion by nNipsx-Sec** [SigmaHQ/pySigma#47] [General]
When process data fields mapping in pipeline file, i want remove some field before generate query.

I found class DropDetectionItemTransformation() use with detection_item_conditions Example 

```
[
            ProcessingItem(
                identifier='windows_remove_eventid',

                transformation = DropDetectionItemTransformation(),
                detection_item_conditions=[ IncludeFieldCondition(fields=["EventID"]) ]
            )
        ] 
```
        
But when use it's have some Error below
        `NotImplementedError: Operator 'and' not supported by the backend`

**Comment by nNipsx-Sec** [comment]
Example sigma rules transformation

```yaml
title: Invoke-Obfuscation Obfuscated IEX Invocation
id: fd0f5778-d3cb-4c9a-9695-66759d04702a
related:
    - id: 51aa9387-1c53-4153-91cc-d73c59ae1ca9
      type: derived
description: 'Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the code block linked in the references'
references: 
    - https://github.com/danielbohannon/Invoke-Obfuscation/blob/master/Out-ObfuscatedStringCommand.ps1#L873-L888
status: experimental
author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
date: 2019/11/08
modified: 2021/09/16
tags:
    - attack.defense_evasion
    - attack.t1027
logsource:
    product: windows
    service: security
fields:
    - ServiceFileName
    - EventID
detection:
    selection:
        EventID: 4697
    selection_1:
        - ServiceFileName|re: '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\['
        - ServiceFileName|re: '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\['
        - ServiceFileName|re: '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\['
        - ServiceFileName|re: '\$env:ComSpec\[(\s*\d{1,3}\s*,){2}'
        - ServiceFileName|re: '\\*mdr\*\W\s*\)\.Name'
        - ServiceFileName|re: '\$VerbosePreference\.ToString\('
        - ServiceFileName|re: '\String\]\s*\$VerbosePreference'
    condition: selection and selection_1
falsepositives:
    - Unknown
level: high
```
