### DISCUSSION TITLE
Proposal: new modifier case sensitive

### DISCUSSION THREAD

**Discussion by vandir** [SigmaHQ/pySigma#84] [Ideas]
As stated in the specification, string values are case sensitive by default. I think it could be helpful to have a new modifier (`insensitive` or just `i`) to search string values for case insensitive matching, that is something like this:

```yaml
detection:
    rule1:
        fieldA|i: value_a
    condition: rule1
```

It could also be chained with `re` modifier to simulate the presence of  flag `re.IGNORECASE` , and obiusly with `contains`, `startswith`, `endswith`, `utf16le` and `utf16be`. In many of my use cases, the presence of such modifier is critical.

If you think this could be useful I can add it and make a PR.
