### ISSUE TITLE
Multiple `condition` with Search-Identifiers that generate `DeferredQueryExpressions` cause repetition

### ISSUE THREAD

**Issue by kelnage** [SigmaHQ/pySigma#126]
The `condition` attribute can be a list of conditions, in which case pySigma will generate multiple queries (generally, one for each condition). However, when finalising these queries, they all [share the same `state` variable](https://github.com/SigmaHQ/pySigma/blob/f34a6592241bfdb426005258ed5b7a73047e93f8/sigma/conversion/base.py#L108C9-L108C9), which contains [a list of all `DeferredQueryExpressions`](https://github.com/SigmaHQ/pySigma/blob/f34a6592241bfdb426005258ed5b7a73047e93f8/sigma/conversion/state.py#L20C10-L20C10) produced by any of those conditions. 

This means that when any rule has multiple condition values and _any_ of them produce `DeferredQueryExpression`s, every generated query will contain **all** of the DeferredQueryExpressions.

As an example, Splunk uses DeferredQueryExpressions for regular expressions, so the following Sigma rule:
```yaml
title: Test
status: test
logsource:
    category: test_category
    product: test_product
detection:
    sel1:
        fieldA|re: valueA
    sel2:
        fieldB|re: valueB
    condition:
        - sel1
        - sel2
```
generates the following queries:
```
*
| regex fieldA="valueA"
| regex fieldB="valueB"

*
| regex fieldA="valueA"
| regex fieldB="valueB"
```
when the expected output would be:
```
*
| regex fieldA="valueA"

*
| regex fieldB="valueB"
```

More than happy to submit a PR with a proposed fix if you'd like!
