### ISSUE TITLE
[Processing pipelines] Transformation to MAP values (not field)?

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/pySigma#182]
Hello, I was looking at PySigma processing pipelines to address this need:

In our rules, to reference a process creation using the Crowdstrike telemetry, we use the following condition:
```yaml
detection:
    selection:
        Event Name: ProcessRollup2
    condition: selection
```
However, there is actually two event in the Crowdstrike telemetry: `ProcessRollup2`, and `SyntheticProcessRollup2` (the second one is for process creations before the crowdstrike agent was fully operationnal).

So, instead of specifying in every rule both process creation events, I'd like a processing pipeline to do it implicitely. So, after the processing pipeline, the rule would actually be:
```yaml
detection:
    selection:
        Event Name:
            - ProcessRollup2
            - SyntheticProcessRollup2
    condition: selection
```

Looking at the available transformations, it seems there is no transformation to do such thing. Am I wrong? 
Thanks!

**Comment by Res260** [comment]
PS: Reading the processing pipelines documentation, the lack of examples for each transformation makes it harder to understand quickly, at least for me :)

**Comment by thomaspatzke** [comment]
You can map a field to multiple fields by specifying them as list, it's described in the [blog post](https://blog.sigmahq.io/connecting-sigma-rule-sets-to-your-environment-with-processing-pipelines-4ee1bd577070) about the transformation. This should do it:

```
transformations:
- id: field_mapping
  type: field_name_mapping
  mapping:
    Event Name:
    - ProcessRollup2
    - SyntchticProcessRollup2
```

The documentation are definitely something that needs improvement 😉

**Comment by Res260** [comment]
@thomaspatzke I don't think this does what I asked. from my understanding, this changes the field NAMES, not VALUES.

From my understanding, this transformation would output a rule that ressembles this:

```yaml
detection:
  selection:
    ProcessRollup2: ProcessRollup2
    SyntheticProcessRollup2: ProcessRollup2
```

whereas what I'm looking for is:

```yaml
detection:
  selection:
    Event Name:
      - ProcessRollup2
      - SyntheticProcessRollup2
```
