### ISSUE TITLE
[Correlations] Issue with rule parsing

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/pySigma#186]
I'm getting my hands on correlations and am trying to support that in our PySigma Backend.

Given this rule taken from the official sigma-specification repo:

```yaml
title: Correlation - Multiple Failed Logins Followed by Successful Login
id: b180ead8-d58f-40b2-ae54-c8940995b9b6
status: experimental
description: Detects multiple failed logins by a single user followed by a successful login of that user
references:
    - https://reference.com
author: Florian Roth (Nextron Systems)
date: 2023/06/16
correlation:
   type: temporal
   rules:
      - multiple_failed_login
      - successful_login
   group-by:
    - User
   timespan: 10m
   ordered: true
falsepositives:
    - Unlikely
level: high
---
id: a8418a5a-5fc4-46b5-b23b-6c73beb19d41
description: Detects multiple failed logins within a certain amount of time
name: multiple_failed_login
correlation:
    type: event_count
    rules:
      - failed_login
    group-by:
      - User
    timespan: 10m
    condition:
      gte: 10
---
id: 53ba33fd-3a50-4468-a5ef-c583635cfa92
description: Detects a single failed login
name: failed_login
logsource:
  product: windows
  service: security
detection:
    selection:
      EventID:
        - 529
        - 4625
    condition: selection
---
id: 4d0a2c83-c62c-4ed4-b475-c7e23a9269b8
description: Detects a successful login
name: successful_login
logsource:
  product: windows
  service: security
detection:
    selection:
        EventID:
          - 528
          - 4624
    condition: selection
```

When I call `SigmaCollection.from_yaml()`, I get this error for the sub-rule with ID `a8418a5a-5fc4-46b5-b23b-6c73beb19d41`:

`sigma.exceptions.SigmaTitleError: Sigma rule must have a title`

If I add a title to that rule, I get the same error, but for the sub-rule with ID `4d0a2c83-c62c-4ed4-b475-c7e23a9269b8`

Is the title mandatory for sub-rules? If so, I'll update the specification examples, because they are misleading :)
