### ISSUE TITLE
Support for regex named capture groups

### ISSUE THREAD

**Issue by joshnck** [SigmaHQ/pySigma#213]
There are times where you need to compare two substrings that you pull apart using Regex and in Splunk you can easily use named capture groups. Consider the following query:

```
index IN (your, ad, logs) EventCode=39
| rex field=Subject "@@@CN=(?<subj_user>[^\.]+)"
| rex field=AccountName "(?<name>[^$]+)"
| eval subj_user=upper(subj_user)
| where subj_user!=name
| table _time AccountName Subject subj_user name
```
If this were doable in Sigma, the rule should look like:

```yaml
title: Certificate Request on Behalf of Another User
id: ec8633a2-d0cf-49c7-92a5-410c0528a6dc
status: test
description: |
    Detects ESC1 escalation path in ADCS environment where an attacker has a compromised account
    and requests a certificate on behalf of another account, likely a domain admin, via a vulnerable
    certifiate template
author: Josh Nickels, Tomasz Dyduch, Marius Rothenbuecher, Balazs Lendvay
date: 2024/04/29
logsource:
    product: windows
    service: system
detection:
    selection_provider:
        Provider_Name: 'Microsoft-Windows-Kerberos-Key-Distribution-Center'
    selection_event:
        eventID: 39
    selection_subject:
        Subject|re: '@@@CN=(?<subj_user>[^\.]+)'
    selection_name:
        AccountName|re: '(?<name>[^$]+)'
    selection_match:
        subj_user|fieldref: name
    condition: selection_provider and selection_event and selection_match
falsepositives:
    - Unknown
level: low
```
Unfortunately, named capture groups are not handled in PySigma to create a new field like they are in Splunk.
