### ISSUE TITLE
Ability to apply rule_conditions to postprocessing

### ISSUE THREAD

**Issue by 0xFustang** [SigmaHQ/pySigma#283]
### Description

Hello! Is there a way to apply `rule_conditions` in a post-processing? The idea would be to apply a post-processing based on a certain condition such as:

```yaml
- type: template
  template: |+
    {{ query }} | extend ServiceName = tostring(ParsedFields.ServiceName) | project foo, bar, ServiceName
  rule_conditions:
    - type: contains_detection_item
      field: "Provider_Name"
      value: "Service Control Manager"

- type: template
  template: |+
    {{ query }} | extend Balance = tostring(ParsedFields.Bar) | project foo, Balance
  rule_conditions:
    - type: contains_detection_item
      field: "Provider_Name"
      value: "balance"
```
