### ISSUE TITLE
Incorrect (outdated?) Documentation

### ISSUE THREAD

**Issue by r0ot** [SigmaHQ/pySigma#299]
`rule_cond_expr`, `detection_item_cond_expr`, `field_name_cond_expr`, `rule_condition_expression`, `detection_item_condition_expression` and `field_name_condition_expression` are all referenced in the documentation but don't exist in code. Moreover, the conditions themselves don't take an `id` parameter (to give them a name), and the conditions can't be specified in the form of a dictionary keyed on the name, either. Is the documentation meant to be aspirational?

Links to documentation in question:
https://github.com/SigmaHQ/pySigma/blob/ad6f3c30c0def1fdb2dbd4a49395caba3b949630/docs/Processing_Pipelines.rst?plain=1#L113-L114
https://github.com/SigmaHQ/pySigma/blob/ad6f3c30c0def1fdb2dbd4a49395caba3b949630/docs/Processing_Pipelines.rst?plain=1#L159-L160
https://github.com/SigmaHQ/pySigma/blob/ad6f3c30c0def1fdb2dbd4a49395caba3b949630/docs/Processing_Pipelines.rst?plain=1#L168-L169

Failing test cases:

1. Fails to parse (with `rule_condition_expresssion` and `rule_cond_expr`)
```yaml
name: Custom Pipeline
priority: 100
transformations:
  - id: logsource_incompatibility
    type: rule_failure
    message: "Log source not compatible"
    rule_condition_expression: "test1 and not test2"
    rule_conditions:
        test1:
            type: logsource
            product: azure
        test2:
            type: logsource
            service: activitylogs
```
2. `LogsourceCondition.__init__() got an unexpected keyword argument 'id'` (with `rule_condition_expresssion` and `rule_cond_expr`)
```yaml
name: Custom Pipeline
priority: 100
transformations:
  - id: logsource_incompatibility
    type: rule_failure
    message: "Log source not compatible"
    rule_condition_expression: "test1 and not test2"
    rule_conditions:
      - type: logsource
        product: azure
        id: test1
      - type: logsource
        service: activitylogs
        id: test2
```
