### ISSUE TITLE
Exception in FieldMappingTransformation when mapping a field name to multiple different

### ISSUE THREAD

**Issue by synacktiv-rj** [SigmaHQ/pySigma#60]
Hello,

There is an issue when a _FieldMappingTransformation_ object is instantiated with a mapping from one field to multiple different.

Indeed, if the mapping is a _list_, `dataclasses.replace` method is called with a _SigmaDetectionItem_ object :

https://github.com/SigmaHQ/pySigma/blob/3e14695e9c8d08dff04b231710d8f1cb54577f56/sigma/processing/transformations.py#L199-L208

The issue is with the field `auto_modifiers` which is an `InitVar`:

https://github.com/SigmaHQ/pySigma/blob/3e14695e9c8d08dff04b231710d8f1cb54577f56/sigma/rule.py#L120

This leads to an exception in `/usr/lib/python3.9/dataclasses.py`: 

`ValueError: InitVar 'auto_modifiers' must be specified with replace()`

When using` dataclasses.replace`, all variables with the `InitVar` specifier from an object must be specified. A simple fix could be like:

`dataclasses.replace(detection_item, field=field, auto_modifiers=detection_item.auto_modifiers) `

If needed, I can provide a testcase to reproduce.

Rémi,

CSIRT Synacktiv

**Comment by thomaspatzke** [comment]
Hi Rémi,

thanks for reporting this, a test case would be great!

**Comment by synacktiv-rj** [comment]
> Hi Rémi,
> 
> thanks for reporting this, a test case would be great!

Hi,

Since pipleline `ecs_zeek_beats` already uses a mapping from one field to multiple different, the rule included bellow should trigger the bug, using python3.9, with this command line:  ``sigma convert --target elasticsearch --pipeline ecs_zeek_beats rule.yml``

```yml
title: Crash in FieldMappingTransformation.apply_detection_item
id: 72ce8669-7e7b-40d0-8956-8014cbe4192b
status: experimental
references:
    - https://github.com/SigmaHQ/pySigma/issues/60
author: Remi Jullian
date: 2022/08/19
logsource:
    category: network
    product: zeek
detection:
    dummy_match:
        cs-host: 'www.google.com'
    condition: dummy_match
fields:
    - cs-host

```
