### ISSUE TITLE
Bug: No `source` or `parent` field in condition with a specific sigma rule

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/pySigma#64]
Steps to reproduce:

Use this rule:
```yaml
title: indicator rule
id: fad282fb-0499-4d3f-9670-55cfc950e2dc
status: stable
level: critical
description: indicator rule
logsource:
  product: Crowdstrike_raw
detection:
  selection:
    QID: 'ProcessRollup2'
    Hostname: 'bitsadmin.exe'
  selection2:
    Hostname: 'bitss.exe'
  condition: selection or selection2
tags:
  - type.indicator
```

1. put a breakpoint in TextQueryBackend (base.py) line 463 as shown here: 
![image](https://user-images.githubusercontent.com/14599855/193433424-5e1c0f11-32d6-45c0-a5df-4ce1447a58bb.png)

2. Debug sigma-cli using this command: `python -m sigma.cli.main convert --target splunk --pipeline sysmon --format default myrule.yml`
3. See when you hit the breakpoint that the AND condition misses information: 
![image](https://user-images.githubusercontent.com/14599855/193433487-5e367498-f243-4187-a895-18a66d28c306.png)

Expected result: the AND condition should have a `parent` and a `source` property that are not `None`.

I know it's weird but I need it for the backend i'm currently building.

Does my explanation make sense?
Thanks for your help :)
