### ISSUE TITLE
TextQueryBackend.convert_condition_group forces DeferredQueryExpression conversion to str

### ISSUE THREAD

**Issue by kelnage** [SigmaHQ/pySigma#69]
Assume a language with the following precedence: (AND, OR) , which translates any unbound string expressions into DeferredQueryExpressions, and supports both AND and OR unbound string queries. Given the following query:
```
title: Test
status: test
logsource:
    category: test_category
    product: test_product
detection:
    keywordA:
        - valueA
        - valueB
    keywordB:
        - valueC
        - valueD
    condition: keywordA and keywordB
```
`TextQueryBackend.convert_condition_group` ([link](https://github.com/SigmaHQ/pySigma/blob/6a83505f6ac64233c7888372ae05026c8adae6b1/sigma/conversion/base.py#L472)) will be called on the DeferredQueryExpressions representing valueA OR valueB and separately on valueC OR valueD. Unfortunately, this will lead to those objects being coerced into str due to the use of the `format` method, and hence appearing as such in the finalised query.

I have a solution (and a forthcoming PR), which is converting the condition and checking whether it is a DeferredQueryExpression before deciding whether to `format` the result or not - but I should note that it would (implicitly) mean any DeferredQueryExpressions used by a backend would have to correctly implement the precedence rules for the language themselves.
