### ISSUE TITLE
Is `all of keywords` supported ?

### ISSUE THREAD

**Issue by gaelmuller** [SigmaHQ/pySigma#72]
I am under the impression that `all of keywords` is not currently supported by pySigma.

The specification says:

> Example: all of keywords means that all items of the list keywords must appear, instead of the default behaviour of any of the listed items.

When testing it, I have the same results for these two rules:

```
detection:
    keywords:
        - EVILSERVICE
        - 42
    condition: keywords
```

```
detection:
    keywords:
        - EVILSERVICE
        - 42
    condition: all of keywords
```
