### ISSUE TITLE
Ignoring unmapped fields as in `Sigmac` tool

### ISSUE THREAD

**Issue by barvhaim** [SigmaHQ/pySigma#82]
Hi @thomaspatzke, in the `Sigmac` tool, fields that were not mapped by the config would be dropped from the query. In the current pySigma pipeline, fields that does not have mapping are left as-is. How do you suggest to implement the same way of dropping parts of the query where fields are not mapped?

**Comment by thomaspatzke** [comment]
It is expected behavior that fields that were not mapped to others are kept in the query. This basically means that the target query should use the same field naming as the Sigma rule, which is valid in many places, e.g. Windows naming. Dropping such fields from queries would change the semantics of the rule and therefore likely break the detection logic it describes. This must be an error in a particular backend or you mean something different. Can you provide an example?

**Comment by barvhaim** [comment]
@thomaspatzke In the context of Sigma to STIX, I want to be able to ignore leaf nodes if their fields does not have mapping, since STIX language has exact requirement for its fields, if I just leave a field unmapped AS-IS it would be illegal STIX query.
For example the rule:
```
title: Test
status: test
logsource:
    category: "process_creation"
    product: "windows"
detection:
    sel1:
        foo: 'bar'
        filename: 'bar'
    condition: sel1
```
would translate to `[(file:name = 'bar')]` using the current Sigmac, because only `filename` has mapping to `file:name` it will ignore the other field to make the query STIX valid at least.

If none of the fields has mapping, then an error will appear for not being able to translate it at all, for example, 

```
title: Test
status: test
logsource:
    category: "process_creation"
    product: "windows"
detection:
    sel1:
        foo: 'bar'
        oof: 'bar'
    condition: sel1
```

translates to an error `An unsupported feature is required for this Sigma rule`.

How do you suggest achieving the same behavior with the new pySigma?
